name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger Docker Image Build and Push
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.CR_PAT }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/geoffreyhayward/february:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/geoffreyhayward/february:latest